### ISSUE TITLE
Node.js headless engine not working. ReferenceError: HTMLElement is not defined

### ISSUE THREAD

**Issue by Hydrosaur** [liabru/matter-js#474]
I get a **ReferenceError** when trying to create an engine in my multiplayer game.
Error:

    C:\Users\USER\Desktop\Projects\PROJECT\node_modules\matter-js\build\matter.js:4391
            return obj instanceof HTMLElement;
                                  ^

    ReferenceError: HTMLElement is not defined
        at Object.Common.isElement (C:\Users\USER\Desktop\Projects\PROJECT\node_modules\matter-js\build\matter.js:4391:31)
        at Object.Engine.create (C:\Users\USER\Desktop\Projects\PROJECT\node_modules\matter-js\build\matter.js:4788:26)
        at Server.<anonymous> (C:\Users\USER\Desktop\Projects\PROJECT\index.js:127:18)
        at Object.onceWrapper (events.js:314:30)
        at emitNone (events.js:110:20)
        at Server.emit (events.js:207:7)
        at emitListeningNT (net.js:1346:10)
        at _combinedTickCallback (internal/process/next_tick.js:135:11)
        at process._tickCallback (internal/process/next_tick.js:180:9)
        at Function.Module.runMain (module.js:607:11)

My requirements for matter.js

	global.document = {
		createElement: function(){
			// Canvas
			return {
				getContext: function() {
					return {};
				}
			};
		}
	};
	var options = {
		render: {
			element: null,
			controller: {
				create: function() {},
				clear: function() {},
				world: function() {}
			}
		},
		input: {
			mouse: {}
		}
	};
	global.window = {};
	var Matter = require('matter-js/build/matter.js');
	var Engine = Matter.Engine,
	World = Matter.World,
	Bodies = Matter.Bodies;
	var engine;

And I create the engine in an http listen function:

	http.listen(PORT, function(){
		console.log('listening on *:' + PORT);
		engine = Engine.create();
		Engine.run(engine);
		setInterval(function(){
			Engine.update(engine, 1000 / 60);
			io.emit('update', utils.playersToPositions(players));
		}, 10);
	});

I pretty sure I'm following the examples well.

**Comment by Hydrosaur** [comment]
Annnnddddd just stumbled upon this issue...

https://github.com/liabru/matter-js/issues/468

**Comment by Hydrosaur** [comment]
Ok, so that didn't help at all.

I still need help with this issue.

**Comment by Hydrosaur** [comment]
It seems this issue is being worked on right now so I'm gonna close this again.

I'm really not good at this git thing.
