### ISSUE TITLE
Doesn't work on nodejs

### ISSUE THREAD

**Issue by LLFourn** [liabru/matter-js#535]
```
> require('matter-js').Engine.create()
TypeError: Cannot read property 'nodeType' of undefined
    at Object.Common.isElement (/root/server/node_modules/matter-js/build/matter.js:4449:23)
    at Object.Engine.create (/root/server/node_modules/matter-js/build/matter.js:4846:26)
    at repl:1:29
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at REPLServer.defaultEval (repl.js:240:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:441:10)
    at emitOne (events.js:120:20)
    at REPLServer.emit (events.js:210:7)
> 
```
```
root@7d42879a986e:~/server# cat node_modules/matter-js/package.json | grep version
    "gulp-tag-version": "^1.3.0",
  "version": "0.14.0"
```

**Comment by liabru** [comment]
Ugh I thought I'd solved that! Looks it needs to handle undefined.

**Comment by AaronPorts** [comment]
Maybe Common.isElement can `return false;` instead of `return !!(obj.nodeType && obj.nodeName)`?

**Comment by Smeky** [comment]
+1

**Comment by AryanJ-NYC** [comment]
@Smeky's workaround worked for me.

**Comment by AryanJ-NYC** [comment]
Thanks @liabru! Fix works for me.
